name: flight_booking_app_using_bloc
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  flutter_bloc: ^9.0.0
  go_router: ^14.8.0
  flutter_form_builder: ^9.7.0
  form_builder_validators: ^11.1.1
  responsive_framework: ^1.5.1
  logger: ^2.5.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/flight.svg
    - assets/images/facebook.svg
    - assets/images/google.svg
